http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  clientes:
    host: localhost
    paths: '/clientes/*'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
serviceEndpoints:
  clienteService:
    url: 'http://localhost:3001'
  httpbin:
    url: 'http://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
