name: Generate SBOM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create SBOM
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Create SBOM with CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@v1
        with: 
          output: './test.app.bom.xml'
      - run: mkdir -p artifact/
          

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: artifact/sbom.cdx.json
